name: Keep Hugging Face Space Alive
on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 10 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request
        run: curl -s https://kohakkun-my-yolo-api.hf.space
